config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'passwords',
    registrations: 'users',
    sessions: 'sessions',
  }

  get '/address', to: 'addresses#show', as: 'address'
  get '/info_window', to: 'info_window#index', as: 'info_window'
  get '/sitemap', to: 'sitemaps#index', as: 'sitemap'

  scope '/sidebar', controller: :sidebar do
    get :search, as: 'search'
    get :combo_form, as: 'combo_form'
    get :edit_profile , as: 'edit_profile'
  end

  resource :reminders
  resource :things
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  root to: 'main#index'
end

app/controllers/sidebar_controller.rb
class SidebarController < ApplicationController
end

app/views/sidebar/_combo_form.html.haml
= form_for :user, :html => {:id => "combo-form", :class => "form-vertical"} do |f|
  %fieldset#common_fields
    .control-group
      %label{:for => "user_email", :id => "user_email_label"}
        = t("labels.email")
        %small
          = image_tag "lock.png", :class => "lock", :alt => t("captions.private"), :title => t("captions.private")
      = f.email_field "email", :value => params[:user] ? params[:user][:email] : nil
    .control-group.radio
      = f.label "new" , radio_button_tag("user", "new", true).html_safe + t("labels.user_new")
      = f.label "existing", radio_button_tag("user", "existing").html_safe + t("labels.user_existing")
  %fieldset#user_sign_up_fields
    .control-group
      %label{:for => "user_name", :id => "user_name_label"}
        = t("labels.name")
        %small
          = t("captions.public")
      = f.text_field "name"
    .control-group
      %label{:for => "user_organization", :id => "user_organization_label"}
        = t("labels.organization")
        %small
          = t("captions.public")
      = f.text_field "organization"
    .control-group
      %label{:for => "user_voice_number", :id => "user_voice_number_label"}
        = t("labels.voice_number")
        %small
          = image_tag "lock.png", :class => "lock", :alt => t("captions.private"), :title => t("captions.private")
      = f.telephone_field "voice_number", :placeholder => t("defaults.voice_number")
    .control-group
      %label{:for => "user_sms_number", :id => "user_sms_number_label"}
        = t("labels.sms_number")
        %small
          = image_tag "lock.png", :class => "lock", :alt => t("captions.private"), :title => t("captions.private")
      = f.telephone_field "sms_number", :placeholder => t("defaults.sms_number")
    .control-group
      %label{:for => "user_password_confirmation", :id => "user_password_confirmation_label"}
        = t("labels.password_choose")
        %small
          = image_tag "lock.png", :class => "lock", :alt => t("captions.private"), :title => t("captions.private")
      = f.password_field "password_confirmation"
    .form-actions
      = f.submit t("buttons.sign_up"), :class => "btn btn-primary"
    %p
      = t("defaults.tos", :tos => link_to(t("titles.tos"), "#tos", :id => "tos_link", :"data-toggle" => "modal")).html_safe
  %fieldset#user_sign_in_fields{:style => "display: none;"}
    .control-group
      %label{:for => "user_password", :id => "user_password_label"}
        = t("labels.password")
        %small
          = image_tag "lock.png", :class => "lock", :alt => t("captions.private"), :title => t("captions.private")
      = f.password_field "password"
    .control-group
      = f.label "remember_me" , f.check_box("remember_me", :checked => true).html_safe + t("labels.remember_me")
    .form-actions
      = f.submit t("buttons.sign_in"), :class => "btn btn-primary"
    %p
      = link_to t("links.forgot_password"), "#", :id => "user_forgot_password_link"
  %fieldset#user_forgot_password_fields{:style => "display: none;"}
    .form-actions
      = f.submit t("buttons.email_password"), :class => "btn btn-primary"
    %p
      = link_to t("links.remembered_password"), "#", :id => "user_remembered_password_link"
= render :partial => "sidebar/tos"
:javascript
  $(function() {
    $('#user_email').focus();
  });

app/views/sidebar/_search.html.haml
= form_tag "/address", :method => "get", :id => "address_form", :class => "search-form" do
  = hidden_field_tag "limit", params[:limit] || 10
  %fieldset.control-group
    = label_tag "city_state", t("labels.city_state"), :id => "city_state_label"
    = select_tag "city_state", "<option value=\"#{t("defaults.city_state")}\" selected=\"selected\">#{t("defaults.city_state")}</option>".html_safe
  %fieldset.control-group
    = label_tag "address", t("labels.address"), :id => "address_label"
    = search_field_tag "address", params[:address], :placeholder => [t("defaults.address_1"), t("defaults.neighborhood")].join(", "), :class => "search-query"
  %fieldset.form-actions
    = submit_tag t("buttons.find", :thing => t("defaults.thing").pluralize), :class => "btn btn-primary"
    %a{:href => edit_user_registration_path, :id => "edit_profile_link", :class => "btn"}
      = t("buttons.edit_profile")
    %a{:href => destroy_user_session_path, :id => "sign_out_link", :class => "btn btn-danger"}
      = t("buttons.sign_out")
:javascript
  $(function() {
    $('#address').focus();
  });

app/views/sidebar/combo_form.html.haml
= render :partial => "combo_form"

app/views/sidebar/edit_profile.html.haml
= form_for resource, :as => resource_name, :url => registration_path(resource_name), :html => {:id => "edit_form", :method => :put} do |f|
  = f.hidden_field "id"
  %fieldset.control-group
    %label{:for => "user_email", :id => "user_email_label"}
      = t("labels.email")
      %small
        = image_tag "lock.png", :class => "lock", :alt => t("captions.private"), :title => t("captions.private")
    = f.email_field "email"
  %fieldset.control-group
    %label{:for => "user_name", :id => "user_name_label"}
      = t("labels.name")
      %small
        = t("captions.public")
    = f.text_field "name"
  %fieldset.control-group
    %label{:for => "user_organization", :id => "user_organization_label"}
      = t("labels.organization")
      %small
        = t("captions.public")
    = f.text_field "organization"
  %fieldset.control-group
    %label{:for => "user_voice_number", :id => "user_voice_number_label"}
      = t("labels.voice_number")
      %small
        = image_tag "lock.png", :class => "lock", :alt => t("captions.private"), :title => t("captions.private")
    = f.telephone_field "voice_number", :placeholder => t("defaults.voice_number"), :value => number_to_phone(f.object.voice_number)
  %fieldset.control-group
    %label{:for => "user_sms_number", :id => "user_sms_number_label"}
      = t("labels.sms_number")
      %small
        = image_tag "lock.png", :class => "lock", :alt => t("captions.private"), :title => t("captions.private")
    = f.telephone_field "sms_number", :placeholder => t("defaults.sms_number"), :value => number_to_phone(f.object.sms_number)
  %fieldset.control-group
    %label{:for => "user_address_1", :id => "user_address_1_label"}
      = t("labels.address_1")
      %small
        = image_tag "lock.png", :class => "lock", :alt => t("captions.private"), :title => t("captions.private")
    = f.text_field "address_1", :placeholder => t("defaults.address_1")
  %fieldset.control-group
    %label{:for => "user_address_2", :id => "user_address_2_label"}
      = t("labels.address_2")
      %small
        = image_tag "lock.png", :class => "lock", :alt => t("captions.private"), :title => t("captions.private")
    = f.text_field "address_2", :placeholder => t("defaults.address_2")
  %fieldset.control-group
    %label{:for => "user_city", :id => "user_city_label"}
      = t("labels.city")
      %small
        = image_tag "lock.png", :class => "lock", :alt => t("captions.private"), :title => t("captions.private")
    = f.text_field "city", :placeholder => t("defaults.city")
  %fieldset.control-group
    %label{:for => "user_state", :id => "user_state_label"}
      = t("labels.state")
      %small
        = image_tag "lock.png", :class => "lock", :alt => t("captions.private"), :title => t("captions.private")
    = f.select "state", us_states, :include_blank => true
  %fieldset.control-group
    %label{:for => "user_zip", :id => "user_zip_label"}
      = t("labels.zip")
      %small
        = image_tag "lock.png", :class => "lock", :alt => t("captions.private"), :title => t("captions.private")
    = f.text_field "zip", :placeholder => t("defaults.zip")
  %fieldset.control-group
    %label{:for => "user_password", :id => "user_password_label"}
      = t("labels.password_new")
      %small
        = t("captions.optional")
    = f.password_field "password"
  %fieldset.control-group
    %label{:for => "user_current_password", :id => "user_current_password_label"}
      = t("labels.password_current")
      %small
        = t("captions.required")
    = f.password_field "current_password"
  %fieldset.form-actions
    = f.submit t("buttons.update"), :class => "btn btn-primary"
    %a{:href => root_path, :id => "back_link", :class => "btn"}
      = t("buttons.back")
:javascript
  $(function() {
    $('#user_email').focus();
  });

app/views/sidebar/search.html.haml
= render :partial => "search"