config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'passwords',
    registrations: 'users',
    sessions: 'sessions',
  }

  get '/address', to: 'addresses#show', as: 'address'
  get '/info_window', to: 'info_window#index', as: 'info_window'
  get '/sitemap', to: 'sitemaps#index', as: 'sitemap'

  scope '/sidebar', controller: :sidebar do
    get :search, as: 'search'
    get :combo_form, as: 'combo_form'
    get :edit_profile , as: 'edit_profile'
  end

  resource :reminders
  resource :things
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  root to: 'main#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :trackable, :validatable
  before_validation :remove_non_digits_from_phone_numbers
  has_many :reminders_from, class_name: 'Reminder', foreign_key: 'from_user_id'
  has_many :reminders_to, class_name: 'Reminder', foreign_key: 'to_user_id'
  has_many :things
  validates :name, presence: true
  validates_formatting_of :email, using: :email
  validates_formatting_of :sms_number, using: :us_phone, allow_blank: true
  validates_formatting_of :voice_number, using: :us_phone, allow_blank: true
  validates_formatting_of :zip, using: :us_zip, allow_blank: true

  def remove_non_digits_from_phone_numbers
    self.sms_number = sms_number.to_s.gsub(/\D/, '').to_i if sms_number.present?
    self.voice_number = voice_number.to_s.gsub(/\D/, '').to_i if voice_number.present?
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  def edit
    render('sidebar/edit_profile', layout: 'sidebar')
  end

  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    if update_resource(resource, account_update_params)
      yield resource if block_given?
      sign_in(resource_name, resource, bypass: true)
      flash[:notice] = 'Profile updated!'
      redirect_to(controller: 'sidebar', action: 'search')
    else
      clean_up_passwords(resource)
      render(json: {errors: resource.errors}, status: 500)
    end
  end

  def create
    build_resource(sign_up_params)
    if resource.save
      yield resource if block_given?
      sign_in(resource_name, resource)
      render(json: resource)
    else
      clean_up_passwords(resource)
      render(json: {errors: resource.errors}, status: 500)
    end
  end

private

  def sign_up_params
    params.require(:user).permit(:email, :name, :organization, :password, :password_confirmation, :sms_number, :voice_number)
  end

  def account_update_params
    params.require(:user).permit(:address_1, :address_2, :city, :current_password, :email, :name, :organization, :password, :password_confirmation, :remember_me, :sms_number, :state, :voice_number, :zip)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_reminder.html.haml
= form_for :reminder, :url => reminders_path, :html => {:id => "reminder_form", :method => "post"} do |f|
  = f.hidden_field "from_user_id", :value => current_user.id
  = f.hidden_field "to_user_id", :value => @thing.user.id
  = f.hidden_field "thing_id", :value => @thing.id
  %fieldset.control-group
    = f.submit t("buttons.send_reminder"), :class => "btn"

app/views/users/profile.html.haml
%h2
  = t("titles.adopted", :thing_name => @thing.name ? @thing.name.titleize : t("defaults.this_thing", :thing => t("defaults.thing")))
  %br
  = t("titles.byline", :name => @thing.user.name)
  %br
  = t("titles.ofline", :organization => @thing.user.organization) unless @thing.user.organization.blank?
- if user_signed_in?
  = render :partial => 'users/reminder'

app/views/users/sign_in.html.haml
%h2
  = t("titles.sign_in", :thing => t("defaults.thing").titleize)

app/views/users/thank_you.html.haml
%h2
  = t("titles.thank_you", :thing => t("defaults.thing"))
= render :partial => 'things/abandon'